project_id = "tkivtvokrnmiimecuowh"

[functions.fetch-pendle-markets]
verify_jwt = false

[functions.analyze-alert]
verify_jwt = false

[functions.dismiss-alert]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.fetch-spectra-markets]
verify_jwt = false

[functions.fetch-exponent-markets]
verify_jwt = false

[functions.fetch-ratex-markets]
verify_jwt = false